enum eMapElementType {
    GROUND,
    WALL
}
// const MapData = [
//     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
//     1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
//     1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
//     1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
//     1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
//     1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
// ];
const MapData = [
    //1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    ["top-left-double",         1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-right-horizon",       1],
    ["top-left-horizon",        1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-horizon-double",      1],
    ["top-right-double",        1],
    //1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
    ["left-vertical-double",    1],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["right-vertical",          0],
    ["left-vertical",           0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["empty",                   0],
    ["right-vertical-double",   1]
];
export default MapData;