var eMapElementType;
(function (eMapElementType) {
    eMapElementType[eMapElementType["GROUND"] = 0] = "GROUND";
    eMapElementType[eMapElementType["WALL"] = 1] = "WALL";
})(eMapElementType || (eMapElementType = {}));
const MapData = [
    ["top-left-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-right-horizon", 1],
    ["top-left-horizon", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-horizon-double", 1],
    ["top-right-double", 1],
    ["left-vertical-double", 1],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["right-vertical", 0],
    ["left-vertical", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["empty", 0],
    ["right-vertical-double", 1]
];
export default MapData;
//# sourceMappingURL=MapData.js.map